[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
runs = 10
max_test_rejects = 100
seed = '0x4242'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
